
services:
#  nvp-api:
#    image: dlacofbs/nvp-api:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
  postgres:
    image: postgres:latset
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - nvp_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: # 마운트할 볼륨 설정
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    restart: always

volumes:
  nvp_pg_data:
    driver: local


